/*
 * Copyright (c) 2014 All Rights Reserved by the SDL Group.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
//--------------------------------------------------------------------------------------
// This file is auto generated by AssemblyInfo.targets on Release build configuration.
//--------------------------------------------------------------------------------------
[assembly: System.Reflection.AssemblyTitle("ISHDeploy.12.0")]
[assembly: System.Reflection.AssemblyDescription("SDL Trisoft ISHDeploy.12.0 2016")]
[assembly: System.Reflection.AssemblyCompany("SDL")]
[assembly: System.Reflection.AssemblyProduct("SDL Knowledge Center ISHDeploy.12.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2003-2016 SDL Group. All rights reserved.")]
[assembly: System.Reflection.AssemblyVersion("0.0.1608.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1608.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.1608.0")]
