<<<<<<< HEAD
//--------------------------------------------------------------------------------------
// This file is auto generated by AssemblyInfo.targets on Release build configuration.
//--------------------------------------------------------------------------------------
[assembly: System.Reflection.AssemblyTitle("ISHDeploy.12.0")]
[assembly: System.Reflection.AssemblyDescription("SDL Trisoft ISHDeploy.12.0 2016")]
[assembly: System.Reflection.AssemblyCompany("SDL")]
[assembly: System.Reflection.AssemblyProduct("SDL Knowledge Center ISHDeploy.12.0")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2003-2016 SDL Group. All rights reserved.")]
[assembly: System.Reflection.AssemblyVersion("0.0.1608.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1608.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.1608.0")]
=======
﻿//------------------------------------------------------------------------------
// This file is auto generated by AssemblyInfo.targets
//------------------------------------------------------------------------------
>>>>>>> Added file Build.props that contains all the variables that might be different for all branches.
