//--------------------------------------------------------------------------------------
// This file is auto generated by AssemblyInfo.targets on Release build configuration.
//--------------------------------------------------------------------------------------
[assembly: System.Reflection.AssemblyTitle("ISHDeploy")]
[assembly: System.Reflection.AssemblyDescription("SDL Trisoft ISHDeploy 2016")]
[assembly: System.Reflection.AssemblyCompany("SDL")]
[assembly: System.Reflection.AssemblyProduct("SDL Knowledge Center ISHDeploy")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © 2003-2016 SDL Group. All rights reserved.")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
