@startuml

title All zone clients integration

node "User zone" {
    [Browser] as B
    [Client Tools] as CT  
    [ISHRemote] as ISHRemote  
} 


node "Server zone" {
    [Security Token Service (STS)] as STS

    node "Content Manager zone" {
        [ISHCM] as ISHCM
    note bottom of ISHCM 
        Accepts tokens from STS
    end note
        [ISHWS] as ISHWS  
    note bottom of ISHWS 
        Accepts tokens from STS
        Accepts tokens from ISHSTS
    end note
        [Non interactive clients] as NIClient
    } 
}

B-u->STS : WS Federation
CT-u->STS : WS Trust
ISHRemote-u->STS : WS Trust
B-r->ISHCM
CT-r->ISHCM
CT-r->ISHWS
ISHRemote-r->ISHWS
NIClient-u->STS : WS Trust
NIClient-r->ISHWS


@enduml


